apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: task-manager
spec:
  type: ClusterIP

  selector:
    app: task-manager-backend

  ports:
    - name: http
      port: 5000
      targetPort: 5000
