---
apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secret
  namespace: task-manager
type: Opaque
stringData:
  POSTGRES_USER: taskuser
  POSTGRES_PASSWORD: taskpassword
  POSTGRES_DB: taskmanagerdb
